services:
  api:
    build: ./Backend
    container_name: bgt-api
    ports:
      - "5018:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - bgt-db:/app/data

  front:
    build: ./Frontentd
    container_name: bgt-front
    ports:
      - "8082:80"
    depends_on:
      - api

volumes:
  bgt-db:
