services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: bgt-mssql
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "${ACCEPT_EULA}"
      MSSQL_PID: "${MSSQL_PID}"
      SA_PASSWORD: "${SA_PASSWORD}"
    volumes:
      - mssql-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"${SA_PASSWORD}\" -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      timeout: 5s
      start_period: 30s
    restart: unless-stopped

  api:
    build: ./Backend
    container_name: bgt-api
    ports:
      - "5018:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: "Server=${DB_HOST};Database=${DB_NAME};User Id=${DB_USER};Password=${SA_PASSWORD};TrustServerCertificate=True;"
    depends_on:
      mssql:
        condition: service_healthy

  front:
    build: ./Frontentd
    container_name: bgt-front
    ports:
      - "8082:80"
    depends_on:
      - api

volumes:
  mssql-data:
